config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :users
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)
    # @order = ShopifyAPI::Order.create(line_items: [{ quantity: 1, variant_id: 31_088_952_541_283 }], financial_status: 'authorized', email: 'foo@example.com')
  end
end

app/views/home/index.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  ShopifyApp.ready(function () {
    ShopifyApp.Bar.initialize({ title: "Home" });
  });
</script>
<% end %>
<h1>Loyalty Program</h1>
<%= link_to 'Customer Points Multiplier Setup', users_path , class: "btn btn-outline-primary"%>
<%= link_to 'Customers Points Balance List', customers_path , class: "btn btn-outline-primary"%>
<hr>
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.title, "https://#{@shop_session.domain}/admin/products/#{product.id}", target: "_top" %></li>
  <% end %>
</ul>

<hr>

<h2>Webhooks</h2>

<% if @webhooks.present? %>
<ul>
  <% @webhooks.each do |webhook| %>
  <li><%= webhook.topic %> : <%= webhook.address %></li>
  <% end %>
</ul>
<% else %>
<p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks
</p>
<% end %>
<hr>